{% set name = "libcflib" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: 58bb8d2a0b0f3e9f823e5fed7fa179fbff510614e77b537bcd929185702d6d45

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cerberus
    - tornado
    - whoosh
    - xonsh
    - zict
    - tqdm
    - toolz
    - jinja2
    - lazyasd
    - pandas

test:
  imports:
    - libcflib
    - libcflib.environ

about:
  home: http://github.com/regro/libcflib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Library Conda Forge Library'

extra:
  recipe-maintainers:
    - scopatz
    - CJ-Wright
    - mariusvniekerk
