travis:
  secure:
    BINSTAR_TOKEN: h2edZteEzN/SLokgnyY/R9hTaCE9i9dLyzjCpYjg2mljyYvt0BC9vcdxMVF8SjNDEY9fW774MqZGtQaLaXkuix+6Vbpl/RFQokdoRtICYRco+AdrSJ2ZtjL1JtzeTZTp6gw7n1JbUgFmquSJA3QJEpb6Mj0oxPGrPALXcHfK1vcUuPoorUsB3bnvfW42kZSVbBmTYXP6E4HG/oc/FqQUBSJ6Se+I2m1qC1TjxgDU3KTwpdpuxQvo+M39PoVxQCwfr+O+KkuRmwvnrYl7dD+rNS0nFYrHOiQfKeGOiHr11ojKXIyFwukzq70D+qosIxv8bUj16+tIWwiZwrsLT++mFEi/n/OwVHRAv15oNCvnQCj8d6NHemDR9x8FPtIgfQyF43IYMohI5bcnpcI0zuMfaglHRcLRr8B0xJf4V/u4iQcQ0p4q0G5kaSXwQ/mX/kiu2N260Pl/09uThDV68Fvh+yZqDpg0Z7ieqb5dKCbdckvl+ujPi2YOhn5Xv5dKe/O8PiEfz+/mwcoTyX0u94BmaHr36FZlAcnZFnY7Y1A4JwL+Yd2tf6wpGEilOmKFldIkrFywt3v5TScZ1en0788N8GFIiffcgbGougTTv9Lrix/9NYghuUCHDQnwfc7x0jgbWvqfWk0VlzlEAGFF+Pgmln0Z1PTcImhgC5zUWXlqqfk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
