travis:
  secure:
    BINSTAR_TOKEN: GR7Oh8+BVtxxxavorC9IQeLyOoBuL7tLuQM2LrI6URrjrlzbJOouSfzh5rr6C2UexeB+xXQlR8dw/tC/9DjISLs6zCgafmm7kD6rSw9o+eWEMrNvFWKVQ4+U3gwFw5HulNcw1JIxsymaMLJEoPHmZJ2nixnsWQpFktdmbs5Olz/ZBxCQ2FCEkEjefpGb2pUyb/p9YkG9zK9NdHL4yjOSOup8oLqdduBWqesEYZihWp581pfGWcHuTh63LAqr8u/BfUT9LlERp2C6Xrqo8/nRhRLCzFPsFHKlO5cLn2Tnzt9hgaKnt1j3RtMOkfPEmxlsQHVoN3fZjtDCQWEcM/Q0LrZ6kKTelkfQUhMGqhSeLOxWY84xVrzeGpXqMuPH57FciJjLOc9AaebSwGmCnj4OfBpYSgA+pTlp+odGpDnkaQRu0tGbMT9rVtf+lcOdKlke2blYCwwG4cDpDNAp0uYDT+qY3SRSqKTE12rJqNkpCEUp9vBKEV4wGgAuqL/BcWosc9FfsSomLOiK2YqzLNLGiufiyNsHGlHuSTHd5tBcr1lc1mx6ofHELDBuvVZV3mcjooFBjnHvSOg3OZpu7tGoq+uwrDoMXHDFG8w6n3u0dnZLQ5n0vNb+B3/TnoA4hpQ5C8Eg3Lb6o1EzfmpB11YGo3j683GzKlSjz28BHD8CWG8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
